---
title: "A function to export GDPM to excel EPIPOI format"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exporting2epipoi}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

Below is a function that queries the GDPM data from a disease `x` (`"mumps"`,
`"measles"`, etc...) and exports the variable `var` (either `"incidence"` or
`"mortality"`) to an excel in a format compatible with
[EPIPOI](http://www.epipoi.info):

```{r}
export2epipoi <- function(x, var = "incidence") {
  require(gdpm)
  require(dplyr)
  require(tidyr)
  require(openxlsx)
  x %>%
    getid_() %>%
    select(year, month, province, starts_with(var)) %>%
    mutate(month = as.integer(month)) %>%
    arrange(year, month) %>%
    spread(province, 4) %>%
    write.xlsx(paste0(x, "_epipoi.xlsx"))
}
```

Let's try it:

```{r}
export2epipoi("mumps")
```

